project_id = "dreeuacqovhldjhlynio"

[functions.send-contact-email]
verify_jwt = false

[functions.reviews]
verify_jwt = false

[functions.create-booking-checkout]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.get-available-times]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
